dbtLego:
  target: dev_snowflake
  outputs:
    dev_snowflake:
      type: snowflake
      account: ${DBT_SNOWFLAKE_ACCOUNT}
      user: ${DBT_SNOWFLAKE_USER}
      password: ${DBT_SNOWFLAKE_PASSWORD}
      role: SYSADMIN
      database: lego_db
      warehouse: my_warehouse
      schema: lego_schema
      threads: 4
      client_session_keep_alive: True