name: dbt CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Run dbt
        env:
          DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER }}
          DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}
          DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
        run: |
          dbt deps --profiles-dir .
          dbt seed --profiles-dir . --target dbtLego --models +models/staging
          dbt run --profiles-dir . --target dbtLego --models +models/staging +models/transformation
          dbt test --profiles-dir . --target dbtLego
          dbt docs generate --profiles-dir . --target dbtLego

      - name: Upload documentation
        uses: actions/upload-artifact@v4.3.3
        with:
          name: dbt-docs
          path: target/